VARIABLE_QUESTIONS = [
  {
    possible_variable_names: [
      "num_fish",
      "num_cats",
      # "num_dogs",
      # "num_steaks",
      # "percent_of_love_maintained",
      # "fav_number",
      # "lucky_number",
      # "unlucky_num",
      # "days_without_rain",
      # "years_without_championship",
    ],
    possible_variable_values: (1..100).to_a.shuffle,
  },
  # {
  #   possible_variable_names: [
  #     "time_abroad",
  #     "period_married",
  #     "time_passed_since_breakup",
  #     "time_elapsed_since_last_vacay",
  #     "waiting_period",
  #     "sentence_length",
  #     "tenure",
  #     "next_train",
  #     "life_span",
  #     "term_length",
  #     "time_in_office",
  #     "incumbency",
  #     "stint_length",
  #   ],
  #   possible_variable_values: [
  #     "#{rand(2..11)} months",
  #     "#{rand(2..11)} months",
  #     "#{rand(2..11)} months",
  #     "#{rand(2..20)} years",
  #     "#{rand(2..20)} years",
  #     "#{rand(2..20)} years",
  #     "#{rand(2..6)} days",
  #     "#{rand(2..6)} days",
  #     "#{rand(2..6)} days",
  #   ].uniq,
  # },
  # {
  #   possible_variable_names: [
  #     "pilot_name",
  #     "point_guard",
  #     "gardener",
  #     "cook",
  #     "chef",
  #     "boss",
  #     "rival",
  #     "opponent",
  #     "foe",
  #     "partner",
  #     "teammate",
  #     "subordinate",
  #     "server",
  #     "trooper",
  #     "peacekeeper",
  #     "best_friend",
  #     "worst_enemy",
  #     "oldest_friend",
  #     "nemesis",
  #     "comrade",
  #     "team_captain",
  #     "instructor_name",
  #     "friend_for_life",
  #     "thief",
  #     "dancer",
  #     "lead_singer",
  #     "drummer",
  #     "guitarist",
  #     "bassist",
  #   ],
  #   possible_variable_values: $random_names_array
  # },
]
